import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "tests/route-zone-time.test.ts",
      "tests/route-deadline-preference.test.ts",
      "tests/route-zones-service.test.ts",
      "tests/route-google-direct.test.ts",
      "tests/route-fleet-constraints.test.ts",
      "tests/route-strict-priority.test.ts",
      "tests/route-strict-priority-live.test.ts",
      "tests/route-map-selection.test.ts",
      "tests/route-early-reception.test.ts",
      "tests/route-traffic-clock.test.ts",
      "tests/route-road.test.ts",
      "tests/route-optimization-google.test.ts",
      "tests/route-logistics-policy.test.ts",
      "tests/route-ai-integration.test.ts",
      "tests/routing.test.ts",
    ],
    fileParallelism: false,
    testTimeout: 30000,
    hookTimeout: 60000,
    coverage: {
      include: [
        "src/core/route-zones.ts",
        "src/core/route-google-direct.ts",
        "src/core/route-fleet-constraints.ts",
        "src/core/route-strict-priority.ts",
        "src/core/route-visit-windows.ts",
        "src/core/route-time-conflicts.ts",
        "src/core/route-reception.ts",
        "src/core/route-traffic-clock.ts",
        "src/core/route-service-time.ts",
        "src/core/route-road.ts",
        "src/core/route-geographic-planner.ts",
        "src/core/route-optimization-google.ts",
      ],
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      reportsDirectory: "coverage/zone-time-focused",
      thresholds: { lines: 95, statements: 95, functions: 95, branches: 90 },
    },
  },
});
